using System.Xml.Serialization;

namespace Loader.SCDb.Xml.Shops
{
	// This is a node in the the RetailProductPrices XML file
	public class Node
	{
		[XmlAttribute]
		public double BasePrice;

		[XmlAttribute]
		public string Directory;

		[XmlAttribute]
		public string Filename;

		[XmlAttribute(AttributeName = "ID")]
		public string Id;

		[XmlAttribute]
		public int Index;

		[XmlAttribute]
		public double ManHours;

		[XmlAttribute]
		public double MaxDiscountPercentage;

		[XmlAttribute]
		public double MaxPremiumPercentage;

		[XmlAttribute]
		public string Name;

		[XmlAttribute]
		public double OutputSPUPerProduction;

		public Node[] RetailProducts;
	}

	public class ShopLayoutNode
	{
		[XmlAttribute]
		public string AcceptsStolenGoods;

		[XmlAttribute]
		public string AutoGenerated;

		[XmlAttribute]
		public string Deletable;

		[XmlAttribute]
		public string Global;

		[XmlAttribute(AttributeName = "ID")]
		public string Id;

		[XmlAttribute]
		public int Index;

		[XmlAttribute]
		public string Name;

		[XmlAttribute]
		public double ProfitMargin;

		[XmlAttribute]
		public string ReadOnly;

		[XmlAttribute]
		public string Renamable;

		public ShopInventoryNode[] ShopInventoryNodes;

		public ShopLayoutNode[] ShopLayoutNodes;

		[XmlAttribute]
		public string SiblingLinkage;

		[XmlAttribute]
		public string Static;
	}

	public class ShopInventoryNode
	{
		[XmlAttribute]
		public string AutoConsume;

		[XmlAttribute]
		public string AutoGenerated;

		[XmlAttribute]
		public string AutoRestock;

		[XmlAttribute]
		public double BasePriceOffsetPercentage;

		[XmlAttribute]
		public string Deletable;

		[XmlAttribute(AttributeName = "ID")]
		public string Id;

		[XmlAttribute]
		public int Index;

		[XmlAttribute]
		public double Inventory;

		[XmlAttribute(AttributeName = "InventoryID")]
		public string InventoryId;

		[XmlAttribute]
		public double MaxDiscountPercentage;

		[XmlAttribute]
		public double MaxInventory;

		[XmlAttribute]
		public double MaxPremiumPercentage;

		[XmlAttribute]
		public string Name;

		[XmlAttribute]
		public double OptimalInventoryLevel;

		[XmlAttribute]
		public string ReadOnly;

		[XmlAttribute]
		public double RefreshRatePercentagePerMinute;

		[XmlAttribute]
		public string Renamable;

		[XmlAttribute]
		public string SiblingLinkage;

		[XmlAttribute]
		public string Static;

		[XmlAttribute]
		public string TransactionType;

		public TransactionType[] TransactionTypes;
	}

	public class TransactionType
	{
		[XmlText]
		public string Data;
	}
}
